import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Home,
  LineChart,
  Package,
  Package2,
  Settings,
  ShoppingCart,
  UsersRound,
} from "lucide-react";
import Sidemenu from "@/components/Sidemenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <main className="flex h-screen bg-zinc-800 fixed w-screen  ">
          {/*Side-menu*/}
          <div>
            <Sidemenu />
          </div>
          {/*Page-content*/}
          <div className="overflow-auto mx-2 w-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
